#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}


hc emit_hook reload


hc unrule --all
hc keyunbind --all
hc mouseunbind --all


hc set default_frame_layout 3

hc set always_show_frame 1
hc set smart_frame_surroundings 0
hc set smart_window_surroundings 0

hc set frame_border_active_color '#9fbc00'
hc set frame_border_normal_color '#454545'
hc set frame_bg_active_color '#000000'
hc set frame_bg_normal_color '#000000'
hc set window_border_active_color '#9fbc00'
hc set window_border_normal_color '#454545'
hc set window_border_urgent_color '#454545'

hc set frame_border_width 2
hc set frame_gap 2
hc set frame_padding 0
hc set window_border_width 2
hc set window_gap -2
hc set snap_gap 2
hc set snap_distance 10

hc pad 0 -2 -2 -2 -2


Mod=Mod4

hc and . rename default 1 . set_layout grid

for i in {1..9} 0; do
	if [[ $i -eq 0 ]]; then
		index=9
	else
		index=$(($i - 1))
	fi

	hc add $i
	hc keybind $Mod-$i use_index $index
	hc keybind $Mod-Shift-$i move_index $index
done

hc keybind $Mod-grave use_previous
hc keybind $Mod-period use_index +1
hc keybind $Mod-comma use_index -1
hc keybind $Mod-Shift-period move_index +1
hc keybind $Mod-Shift-comma move_index -1

hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

hc keybind $Mod-space cycle_layout +1
hc keybind $Mod-Shift+space cycle_layout -1

hc keybind $Mod-r remove
hc keybind $Mod-y split left
hc keybind $Mod-u split bottom
hc keybind $Mod-i split top
hc keybind $Mod-o split right

hc keybind $Mod-h focus left
hc keybind $Mod-j focus down
hc keybind $Mod-k focus up
hc keybind $Mod-l focus right
hc keybind $Mod-Shift-h shift left
hc keybind $Mod-Shift-j shift down
hc keybind $Mod-Shift-k shift up
hc keybind $Mod-Shift-l shift right
hc keybind $Mod-Control-h resize left +0.01
hc keybind $Mod-Control-j resize down +0.01
hc keybind $Mod-Control-k resize up +0.01
hc keybind $Mod-Control-l resize right +0.01

hc keybind $Mod-Up focus up
hc keybind $Mod-Down focus down
hc keybind $Mod-Left focus left
hc keybind $Mod-Right focus right
hc keybind $Mod-Shift-Up shift up
hc keybind $Mod-Shift-Down shift down
hc keybind $Mod-Shift-Left shift left
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Control-Up resize up +0.01
hc keybind $Mod-Control-Down resize down +0.01
hc keybind $Mod-Control-Left resize left +0.01
hc keybind $Mod-Control-Right resize right +0.01

hc keybind $Mod-Tab cycle +1
hc keybind $Mod-Shift-Tab cycle -1

hc keybind $Mod-Shift-c close

hc keybind $Mod-Return spawn urxvt
hc keybind $Mod-backslash spawn dmenu_run -i -b -nb '#454545' -nf '#9fbc00' -sb '#9fbc00' -sf '#454545' -p 'exec:'
hc keybind $Mod-semicolon spawn /usr/share/doc/herbstluftwm/examples/herbstcommander.sh
hc keybind $Mod-Print spawn scrot
hc keybind $Mod-Shift-apostrophe spawn slock

hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize


hc rule focus=off
hc rule class='Chromium' focus=on
hc rule class='MPlayer' focus=on
hc rule class='URxvt' focus=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' pseudotile=on focus=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_SPLASH' pseudotile=on


hc unlock
